### ISSUE TITLE
Get new reviews from latestreview.txt

### ISSUE THREAD

**Issue by alemela** [factsmission/twee-fi-aggregator#3]
In the file it appears the latest review made by the user.

**Comment by alemela** [comment]
Strange error because I don't want to parse the file...

        throw new Error('Error trying to parse <' + base + '> as ' + contentType + ':\n' + e + ':\n' + e.stack);
        ^

Error: Error trying to parse <https://alemela.solidtest.space/public/twee-fi/latestReview.txt> as text/plain:
Error: Don't know how to parse text/plain yet:
Error: Don't know how to parse text/plain yet

**Comment by retog** [comment]
There used to be only RDF files, now there's also this text file there. Just skip it when reading the data.
